#!/usr/bin/env bash
# Per-project configuration for ios-build-verify (Conjuguer).
# Generated by setup_project.sh; safe to hand-edit.
APP_NAME=Conjuguer
BUNDLE_ID=software.racecondition.Conjuguer
PROJECT=Conjuguer.xcodeproj
SCHEME=Conjuguer
TARGET_SIM='iPhone 17'
FIRST_SCREEN_ID=verb_browse_sort
MAIN_TABS=(verbs models quiz info settings)
MAIN_TABS_COORDS=("63,817.7" "132,817.7" "200.7,817.7" "269.3,817.7" "338.5,817.7")
WAIT_FOR_RENDER_BUDGET_S=10
MAIN_TABS_COUNT_ACK=""
ONBOARDING_DISMISS_LABEL=''
